name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Build Debug APK
      run: |
        gradle --version
        gradle assembleDebug

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: HeshamppFull-APKs
        path: app/build/outputs/apk/**/**/*.apk
